### PR TITLE
Getting the midi value of a note

### PR DESCRIPTION
**Pull request by mattconstantine**
How about a toMIDI to compliment fromMIDI?

### CODE REVIEW

**Comment by saebekassebil** [comment]
Actually we've already had this suggested before - and I said "no more sugar to this library" (issue #51). But until this library gets refactored into smaller modules - screw it. Let's do it!

Could you call it `.midi()` and add the documentation next to `note.key()`? That'd be perfect.

Thank you Matt!

**Comment by mattconstantine** [comment]
Cool. I made the changes. Does that look good?

**Comment by saebekassebil** [comment]
I believe you've forgot to change the actual method's name?

**Comment by saebekassebil** [comment]
Took the liberty of fixing that last bit myself - Cheers anyway Matt!

**Comment by mattconstantine** [comment]
Good catch :) Thanks for the merge!

**Pull request merged**
