### PR TITLE
Scale.get

### PR DESCRIPTION
**Pull request by jaylupus**
Extended 'Scale.get' function to get notes outside of octave range. Added tests.

### CODE REVIEW

**Comment by saebekassebil** [comment]
Very cool! I'll just have to check the tests when I get home to my computer.

Thank you for you contribution jaylupus (:

**Comment by saebekassebil** [comment]
I'm not sure how the negative numbers should work. As of now I get a `RangeError` infinite-loop when trying to get `scale.get(0), scale.get(-7), scale.get(-14), etc`

Also it seems a bit counter-intuitive that `scale.get(-1)` isn't just one note down from unison? But I guess we have to keep that way

**Comment by saebekassebil** [comment]
So I've added the functionality you've implemented. And thanks for that - it was an obvious addition to make to that method :)

Please let me now if it works out for you the way you expect. (and sorry for the late answer)

**Comment by jaylupus** [comment]
Thank you, I'll do so.

**Pull request merged**
