### PR TITLE
Fix blues scale

### PR DESCRIPTION
**Pull request by alexesDev**

### CODE REVIEW

**Comment by saebekassebil** [comment]
Cheers Alexey, but.. Why `d5` instead of `A4`? Do you have any sources you could link to?

**Comment by alexesDev** [comment]
Blues scale consists of the minor pentatonic scale plus the *diminished* 5th. Wikipedia say "plus the ♯4th or ♭5th degree", but in many other literature says only "plus the *diminished* 5th".

**Comment by saebekassebil** [comment]
Could you link to a few of those sources? I know I'm being a bit pedantic, but I guess so is this change ;)

**Comment by alexesDev** [comment]
http://www.andydrudy.com/lessons/Blues.pdf
http://www.abington.k12.pa.us/copper/pdf/Guitar%20Club/The%20pentatonic%20scale.pdf
http://www.guitarsrecycled.com/chords.html
http://www.guitarmasterclass.net/wiki/index.php/The_Minor_Pentatonic_and_Blues_Scales_(lesson)
And many others... And I develop a music tool and I received a comment from the music teacher about blues note =)

**Comment by saebekassebil** [comment]
Well, I'm convinced - We're doing it, although I had to bump the major to version `2.0.0`.

So: per `teoria@2.0.0` the blues scale has a diminished fifth instead of an augmented fourth.

Thanks for the contribution Alexey!

**Pull request merged**
