### PR TITLE
Fix #59 : add chord.bass and chord.inverted()

### LINKED ISSUE #59: Create a chord with root different from the tone
Hi,

Not sure about the correct english name of what i want to explain, an exemple worth 10000 words. 

I dont find the way to build such a chord : ``A/B`` : A chord with ``A``  as the tonic and ``B`` as the bass.

Is there a way to do so in the current version ?

### PR DESCRIPTION
**Pull request by gsouf**
Fix #59
I added a few testes, but i didnt run the tests. I didnt know how to run them (i'm not a javascript hacker!)

### CODE REVIEW

**Comment by saebekassebil** [comment]
Thank you very much for doing this @SneakyBobito!

I think that the `chord.bass` property needs to be converted into a method `chord.base()` because the voicing of a chord can be altered! E.g:

```js
var am = teoria.chord('Am');
am.base().name() == 'a';
am.voicing(['P5', 'P1', 'm3']);
am.base().name() == 'e';
```
I like the `.inverted()`! Could you add some tests?

You can run the test be running `npm test` in the project root.

**Comment by SneakyBobito** [comment]
I will, adapt the PR asap. Stay tunned

**Comment by SneakyBobito** [comment]
Is there a way to check if two teoria.note are the same note no matter about the pitch ?

**Comment by saebekassebil** [comment]
What do you mean "no matter the pitch?".

**Comment by SneakyBobito** [comment]
I'm looking if two notes are the sames.

For instance a ``A`` low and a ``A`` high are both a ``A``.

**Comment by saebekassebil** [comment]
`note.toString(true)` gives you the note name without the octave number

**Comment by saebekassebil** [comment]
Hi @gsouf - I went ahead and implemented the `Chord#bass()` function, which basically just returns the note voiced the lowest. Hope you'll find it useful!

**Comment by gsouf** [comment]
Hey @saebekassebil 
Sorry, my project with teoria has not been updated for weeks, I forgot this issue !

Thank you

**Pull request closed without merging**
